
# The Planes are slightly overscaled to avoid seeing the edges when the camera moves

{
  "Arena": [
    { "Name": "Floor", "MeshType": "Plane", "Translation": [0.049, -0.04, 1.94248],"Scale": [0.63, 0.63, 0.1], "Rotation": [-1.57, 0.0, 0.0], "AmbientColor": [1, 1, 1], "DiffuseColor": [1, 1, 1], "SpecularColor": [0, 0, 0], "Texture": "Rocks", "Repetitions": 2,"RepeatInterval": 0.62832},
  ],

} 