name: Zip Examples Folders

on:
  push:
    tags:
      - '*'

jobs:
  zip-folders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip utility
      run: sudo apt-get install -y zip

    - name: Zip each subfolder
      run: |
        for lab in $(find . -maxdepth 1 -type d ! -name '.*' ! -name '.' | sed 's|./||'); do
          for example in $(find $lab -maxdepth 1 -type d ! -name '.*' ! -name $lab); do
            zip -r "${lab}-${example##*/}.zip" "$example"
          done
        done

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Upload zip files to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: '*.zip'
        asset_name: ${{ github.ref }}-examples.zip
        asset_content_type: application/zip